webhost: admin.fisl16.softwarelivre.org
webport: 80
sitename: admin
master_host: fisl16.softwarelivre.org
api_host: http://segue-api.fisl16.softwarelivre.org
api_path: /api
app_path: /var/www/admin.{{ master_host }}
